// Auto-generated by `npx boneyard-js build`
import { registerBones } from 'boneyard-js'

import _login_form from './login-form.bones.json'
import _register_form from './register-form.bones.json'

registerBones({
  "login-form": _login_form,
  "register-form": _register_form,
})
